In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('credit.csv')
df

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
5,6,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
6,7,20.996,3388,259,2,37,12,Female,No,No,African American,203
7,8,71.408,7114,512,2,87,9,Male,No,No,Asian,872
8,9,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
9,10,71.061,6819,491,3,41,19,Female,Yes,Yes,African American,1350
10,11,63.095,8117,589,4,30,14,Male,No,Yes,Caucasian,1407
11,12,15.045,1311,138,3,64,16,Male,No,No,Caucasian,0
12,13,80.616,5308,394,1,57,7,Female,No,Yes,Asian,204
13,14,43.682,6922,511,1,49,9,Male,No,Yes,Caucasian,1081
14,15,19.144,3291,269,2,75,13,Female,No,No,African American,148
15,16,20.089,2525,200,3,57,15,Female,No,Yes,African American,0
16,17,53.598,3714,286,3,73,17,Female,No,Yes,African American,0
17,18,36.496,4378,339,3,69,15,Female,No,Yes,Asian,368
18,19,49.570,6384,448,1,28,9,Female,No,Yes,Asian,891
19,20,42.079,6626,479,2,44,9,Male,No,No,Asian,1048
20,21,17.700,2860,235,4,63,16,Female,No,No,Asian,89
21,22,37.348,6378,458,1,72,17,Female,No,No,Caucasian,968
22,23,20.103,2631,213,3,61,10,Male,No,Yes,African American,0
23,24,64.027,5179,398,5,48,8,Male,No,Yes,African American,411
24,25,10.742,1757,156,3,57,15,Female,No,No,Caucasian,0
25,26,14.090,4323,326,5,25,16,Female,No,Yes,African American,671
26,27,42.471,3625,289,6,44,12,Female,Yes,No,Caucasian,654
27,28,32.793,4534,333,2,44,16,Male,No,No,African American,467
28,29,186.634,13414,949,2,41,14,Female,No,Yes,African American,1809
29,30,26.813,5611,411,4,55,16,Female,No,No,Caucasian,915
...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,35.610,6135,466,4,40,12,Male,No,No,Caucasian,992
371,372,39.116,2150,173,4,75,15,Male,No,No,Caucasian,0
372,373,19.782,3782,293,2,46,16,Female,Yes,No,Caucasian,840
373,374,55.412,5354,383,2,37,16,Female,Yes,Yes,Caucasian,1003
374,375,29.400,4840,368,3,76,18,Female,No,Yes,Caucasian,588
375,376,20.974,5673,413,5,44,16,Female,No,Yes,Caucasian,1000
376,377,87.625,7167,515,2,46,10,Female,No,No,African American,767
377,378,28.144,1567,142,3,51,10,Male,No,Yes,Caucasian,0
378,379,19.349,4941,366,1,33,19,Male,No,Yes,Caucasian,717
379,380,53.308,2860,214,1,84,10,Male,No,Yes,Caucasian,0
380,381,115.123,7760,538,3,83,14,Female,No,No,African American,661
381,382,101.788,8029,574,2,84,11,Male,No,Yes,Caucasian,849
382,383,24.824,5495,409,1,33,9,Male,Yes,No,Caucasian,1352
383,384,14.292,3274,282,9,64,9,Male,No,Yes,Caucasian,382
384,385,20.088,1870,180,3,76,16,Male,No,No,African American,0
385,386,26.400,5640,398,3,58,15,Female,No,No,Asian,905
386,387,19.253,3683,287,4,57,10,Male,No,No,African American,371
387,388,16.529,1357,126,3,62,9,Male,No,No,Asian,0
388,389,37.878,6827,482,2,80,13,Female,No,No,Caucasian,1129
389,390,83.948,7100,503,2,44,18,Male,No,No,Caucasian,806
390,391,135.118,10578,747,3,81,15,Female,No,Yes,Asian,1393
391,392,73.327,6555,472,2,43,15,Female,No,No,Caucasian,721
392,393,25.974,2308,196,2,24,10,Male,No,No,Asian,0
393,394,17.316,1335,138,2,65,13,Male,No,No,African American,0
394,395,49.794,5758,410,4,40,8,Male,No,No,Caucasian,734
395,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
396,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
397,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
398,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
399,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
data = pd.read_csv('test.csv', index_col=False, header=0)
x = data.c1.values
y = data.c2.values
print x # prints: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]

NameError: name 'values' is not defined